### ISSUE TITLE
Add Geolosys integration

### ISSUE THREAD

**Issue by benbenlaw** [frank89722/JourneyMapIntegration#1]
I wonder how possible it would be to add geolosys support for there samples that spawn in world. Like shift right click to add a waypoint
![image](https://user-images.githubusercontent.com/42780877/133465429-c29f3eeb-b9df-40dd-8d4b-218af82f6d6c.png)

**Comment by frank89722** [comment]
[jmi-1.16.5-0.4-dev.jar](https://www.dropbox.com/s/pirdq29uvih3ps5/jmi-1.16.5-0.4-dev.jar?dl=1)

I implemented it as a clickable chat message to create a waypoint and trigger by shift right-click on an ore sample but I don't know this is a good idea or not.

Can you give this a try?

**Comment by benbenlaw** [comment]
Yeah I will give it a try tommorow. I wonder if you can make it as a tag. So for example giving a block your tag would make it a shift right clickable event to create the waypoint

**Comment by frank89722** [comment]
Okay that sounds better than how this thing is implemented currently, I'll do it later this week maybe (a bit busy IRL)

**Comment by benbenlaw** [comment]
yeah no worries pretty busy as well lol

**Comment by frank89722** [comment]
Hello! This is added in 0.4-21 and it's on curseforge now.
I end up just make it a list for existing tags (also support block id) since people can create a tag easily with kubejs or datapack.

**Comment by benbenlaw** [comment]
this seems to have stopped working in the latest update

**Comment by frank89722** [comment]
please open a new issue with more information
can't reproduce in my dev environment
