### ISSUE TITLE
[Request] Add FTBChunks claim rendering toggle

### ISSUE THREAD

**Issue by Mylezz** [frank89722/JourneyMapIntegration#12]
ATM7
Forge Ver 1.18.2 - 40.1.31
Journey map int Ver 1.18.2-0.09-45

I want to be able to toggle visibility for the FTB Chunks rendering on the minimap/main map but there is no way to do so. I have looked around but I cannot find a way to get it to disable render except when I disable the entire map from rending. it's annoying when I want to see my base on the map but the entire region I have claimed is tinted green.

**Comment by frank89722** [comment]
I'll add a quick toggle for that.
For now, you can just change `claimedChunkOverlayOpacity` to a lower value for visibility.

**Comment by Mylezz** [comment]
Tyvm!

**Comment by DarQuing** [comment]
Getting an error related to FTB Chunks, which I don't have in this pack. Is there a hard dependency for FTB Chunk now?

**Comment by frank89722** [comment]
@DarQuing That's not related to this issue, please open a new issue for that

**Comment by recon88** [comment]
Any updates? I really would like to turn it off on the minimap but keep it on the big map.

**Comment by frank89722** [comment]
> Any updates? 

For now, this feature is half-implemented on my end and will require journeymap-v5.9+ to work, but seems like it was released with breaking changes in API so it may take some time

> I really would like to turn it off on the minimap but keep it on the big map.

As far as I know, there is no good or efficient way to implement an overlay for just minimap or big map but I'll see what I can do when I have time (busy IRL)

**Comment by frank89722** [comment]
> I'll add a quick toggle for that.

Added in 0.13 (require Journeymap 5.9+ to work correctly)
