### ISSUE TITLE
[Request] Display FTB Chunks Claim and Force-Load Count/Max Values

### ISSUE THREAD

**Issue by Brittank88** [frank89722/JourneyMapIntegration#13]
I still have to use the default FTBC map to see how many chunks I've claimed and force-loaded, and how many more I can do that for. It would be nice if it was displayed neatly somewhere.

**Comment by frank89722** [comment]
That feature is already in the mod, isn't it?
what is your JMI version ?

**Comment by frank89722** [comment]
Forget it, I have subscribed to the wrong event in forge
Thank you for bringing this to my attention

**Comment by frank89722** [comment]
Should be fixed in [lastest version](https://modrinth.com/mod/journeymap-integration/version/jmi-forge-1.18.2-0.12-17)

**Comment by Brittank88** [comment]
> Forget it, I have subscribed to the wrong event in forge Thank you for bringing this to my attention

Heads up - I was on Fabric, so I'm not sure if you have fixed it there too (I'll check it out) but if you haven't, it's an issue on Fabric too.

**Comment by frank89722** [comment]
> Heads up - I was on Fabric, so I'm not sure if you have fixed it there too (I'll check it out) but if you haven't, it's an issue on Fabric too.

Hmm, it could be some other problem if it's on Fabric, just let me know if it still not work.

It should look like this if it's working 
![CleanShot 2022-07-17 at 23 01 00](https://user-images.githubusercontent.com/10683361/179404329-cbedad60-c5ff-486e-a96e-f8bb29ce008e.png)
