### ISSUE TITLE
Single Player "Joining World" Stuck

### ISSUE THREAD

**Issue by JustHmm** [frank89722/JourneyMapIntegration#14]
When you create a singleplayer world, game stuck in "joining world" screen.

Forge 41.0.99
MC 1.19
architectury-5.9.31-forge.jar
ftb-chunks-forge-1900.3.7-build.154.jar
ftb-library-forge-1900.3.7-build.131.jar
ftb-teams-forge-1900.2.7-build.56.jar
journeymap-1.19-5.8.5rc5-forge.jar
jmi-forge-1.19-0.12-10.jar

**Comment by frank89722** [comment]
forge 41.0.94+ support has been added in [jmi-1.19-0.12-19](https://modrinth.com/mod/journeymap-integration/version/jmi-forge-1.19-0.12-19)
