### ISSUE TITLE
Waystone name stays in Journeymap after waystone is broken.

### ISSUE THREAD

**Issue by paplaukes** [frank89722/JourneyMapIntegration#15]
I started a base on a cliff with village waystone way under, at water level.
I added my own waystone for convenience and then broke the village waystone, but - both names show on minimap (map as well). Is there a way to remove old name for a waystone that no longer exists?
![waystone text](https://user-images.githubusercontent.com/87232394/184534604-4a6dbf9d-00e5-4f27-a480-724874245f99.png)

**Comment by frank89722** [comment]
what's your mc, journeymap, jmi version and what mod loader you're running

**Comment by paplaukes** [comment]
MC version 1.18.2, Forge 40.1.68, jei-1.18.2-forge-10.1.3.240, jmi-forge-1.18.2-0.13-25

**Comment by paplaukes** [comment]
Seems issue sorted itself out after second fresh launch of MC. It's been a little glitchy with minimap before too. For example, when I added own waystone, minimap got blocked out by what seemed a huge dark green blurry icon. Had to relaunch MC too. Sorry I don't have screenshots for that. Will just keep playing and post if something comes up.

**Comment by frank89722** [comment]
> ...... jmi-forge-1.18.2-0.13-25

So I believe you're using Journeymap 5.9 beta?
If it's true, this should report to Journeymap issue tracker with more information(logs, etc.), I guess there is nothing I can do since I'm just using the Journeymap API


> Seems issue sorted itself out after second fresh launch of MC. It's been a little glitchy with minimap before too. For example, when I added own waystone, minimap got blocked out by what seemed a huge dark green blurry icon. Had to relaunch MC too. Sorry I don't have screenshots for that. Will just keep playing and post if something comes up.

For now, you could try Journeymap-5.8 with jmi-0.12 and see if is work

**Comment by paplaukes** [comment]
Sorry, I assumed journeymap filename would be the version. I'm using Journeymap-5.8.5 at the moment. Will try that with jmi-0.12, drop to 5.8 if need be.

**Comment by frank89722** [comment]
Okay, I'll look into it since it happened in JM5.8.x
Btw, have you disabled the Journeymap compact that includes in Waystones mod?

**Comment by paplaukes** [comment]
I'm not sure what Journeymap compact is? I see no mod/dependency/file like that. Haven't touched Waystones configuration.

**Comment by paplaukes** [comment]
Maybe you meant this, then no I haven't. Should I?
![image](https://user-images.githubusercontent.com/87232394/184543722-c70acc83-336d-4ff7-8be7-e275660ac9c0.png)

**Comment by frank89722** [comment]
> Maybe you meant this, then no I haven't. Should I? ![image](https://user-images.githubusercontent.com/87232394/184543722-c70acc83-336d-4ff7-8be7-e275660ac9c0.png)

Yes, you should disable it if you want to use the waystone compact from JMI. 
I know it's a bit confusing :/

**Comment by paplaukes** [comment]
Thank you. I'll disable the setting and test when I have some more time.

**Comment by aelfwyne** [comment]
> Maybe you meant this, then no I haven't. Should I? ![image](https://user-images.githubusercontent.com/87232394/184543722-c70acc83-336d-4ff7-8be7-e275660ac9c0.png)

Where are you finding that configuration option?

> > Maybe you meant this, then no I haven't. Should I? ![image](https://user-images.githubusercontent.com/87232394/184543722-c70acc83-336d-4ff7-8be7-e275660ac9c0.png)
> 
> Yes, you should disable it if you want to use the waystone compact from JMI. I know it's a bit confusing :/

The fact that option is NOT present in the journeymap config screen is the problem. I have fought for weeks trying to figure out why I couldn't turn off these waypoint labels.
