### ISSUE TITLE
[Feature Request] Minecolonies Integration

### ISSUE THREAD

**Issue by kreezxil** [frank89722/JourneyMapIntegration#2]
Minecolonies for the longest time has had colony claims that work like FTB Utilities/Chunks claims.

It would be great if you can integrate Minecolonies claims into Journeymap as well.

Currently interested in 1.16.5+ integration.

**Comment by mysticdrew** [comment]
I believe minecolonies already has support for journeymap in their newer versions. 
Per this commit: https://github.com/ldtteam/minecolonies/commit/fc7b4cfc0dc5b27707e0d9c73d0c722a7df86644

**Comment by kreezxil** [comment]
interesting
