### ISSUE TITLE
[1.20.1] Crash on FTB Chunk Claim

### ISSUE THREAD

**Issue by Peach774** [frank89722/JourneyMapIntegration#22]
https://hastebin.skyra.pw/uciretubeb.nestedtext

Probably something to do with the recommended version of forge.

**Comment by frank89722** [comment]
that link is a blank page😢

**Comment by Peach774** [comment]
> that link is a blank page😢

Sorry - just gonna upload the log directly I guess: 
[crash-2023-07-10_10.54.35-client.txt](https://github.com/frank89722/JourneyMapIntegration/files/12017531/crash-2023-07-10_10.54.35-client.txt)

**Comment by frank89722** [comment]
Should be fixed in 0.14-42
Thank you for your report😎
