### ISSUE TITLE
Random NPE Crash

### ISSUE THREAD

**Issue by Gaider10** [frank89722/JourneyMapIntegration#23]
https://github.com/frank89722/JourneyMapIntegration/blob/main/Fabric/src/main/java/me/frankv/jmi/mixin/MouseHandlerMixin.java#L23 doesn't check if the hitResult is null, this normally doesn't happen in vanilla but it's marked as @Nullable and some mods seem to set it to null which sometimes causes random crashes

**Comment by frank89722** [comment]
Thank you for the report!
