### ISSUE TITLE
Setting does not save when switching dims

### ISSUE THREAD

**Issue by frank89722** [frank89722/JourneyMapIntegration#26]
May be related - toggling the FTB chunks overlay off & then entering another dimension toggles the overlay back on, but the button continues to incorrectly reflect an off state

_Originally posted by @sethwalker1 in https://github.com/frank89722/JourneyMapIntegration/issues/18#issuecomment-2016922431_

**Comment by sethwalker1** [comment]
Produced on Forge 47.2.20 / MC 1.20.1
- JourneyMap 5.9.18p1
- JMI 0.14-45
- FTB Chunks 2001.2.5

**Comment by frank89722** [comment]
@sethwalker1 have you tried with newest version ?
this has been fixed in 1.20.1 weeks ago
