### ISSUE TITLE
[Bug] Re-entering a server with disabled FTB Chunks render overlay, partially toggles the overlay on

### ISSUE THREAD

**Issue by DedMaxim** [frank89722/JourneyMapIntegration#28]
If, upon leaving a server, FTB Chunks overlay is turned off, entering the same server will cause the map to partially or fully render some claims. Turning the overlay on and off fixes the issue until the next time the server is re-entered.
Video demonstration:
https://drive.google.com/file/d/1uOx6LnKBWhGbTG33AXcWPGUzaX_QtBUs/view?usp=sharing

Environment:
Intel Xeon E5-2680v2
Nvidia GTX 1070
4x8Gb DDR3 ECC REG RAM
Windows 10 22H2

Minecraft 1.20.1
Forge 47.2.20
Architectury 9.2.14
FTB Chunks 2001.2.7
FTB Library 2001.1.5
FTB Teams 2001.2.0
Journeymap 5.9.20
JMI 0.14-45

**Comment by DedMaxim** [comment]
Seems to be linked with #26 #18

**Comment by frank89722** [comment]
Should be fixed in v1.2
