### ISSUE TITLE
Server Neoforge 1.21.1 Game Crash

### ISSUE THREAD

**Issue by flyover0112** [frank89722/JourneyMapIntegration#31]
Neoforge Server 1.21.1 Neoforge Version 21.1.42
When trying to select chunks or make active chunks through Journeymap, the game crashes and exits.

Server Console log:
[00:34:51] [Netty Epoll Server IO #3/ERROR] [minecraft/Connection]: Exception caught in connection
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
[00:34:51] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Fly0ver lost connection: Disconnected
[00:34:51] [Server thread/INFO] [minecraft/MinecraftServer]: Fly0ver left the game
[crash-2024-09-20_08.34.49-client.txt](https://github.com/user-attachments/files/17068252/crash-2024-09-20_08.34.49-client.txt)

**Comment by BlexsYT** [comment]
Same issue here, only crashed on the client, when claiming using the Integration in Journeymap screen it closes the game.

**Comment by frank89722** [comment]
Seems like there are some breaking changes in recent FTBChunks update, I'll take a look in next few days

**Comment by frank89722** [comment]
Should be fixed in v1.6
