### ISSUE TITLE
ThemeLabelSourceMixin

### ISSUE THREAD

**Issue by mysticdrew** [frank89722/JourneyMapIntegration#5]
So not really an issue. Looking through your code, I think I will modify the info slots so that addons can add more as they wish and not have ThemeLabelSource be an enum. 

I encourage you to join our discord ([JourneymapDiscord](https://discord.gg/eP8gE69)) so you can give insight on other things you want in the api as I am doing a ton of work on the API right now.

**Comment by frank89722** [comment]
> So not really an issue. Looking through your code, I think I will modify the info slots so that addons can add more as they wish and not have ThemeLabelSource be an enum.

This sounds great

> I encourage you to join our discord ([JourneymapDiscord](https://discord.gg/eP8gE69)) so you can give insight on other things you want in the API as I am doing a ton of work on the API right now.

I have joined and asked for adding the button part to API if it's possible. thank's again for your invitation :)
