### ISSUE TITLE
Unwanted Waystone Text on Screen when Minimap at Bottom Right

### ISSUE THREAD

**Issue by Hjaldar** [frank89722/JourneyMapIntegration#7]
See included images:
![2022-01-23_04 22 33](https://user-images.githubusercontent.com/3286136/150649408-5e1e4195-60b9-40d2-b5c1-7a8cebf54650.png)
![2022-01-23_04 23 04](https://user-images.githubusercontent.com/3286136/150649410-4510daea-f9e6-4427-88a9-0ddec708ae11.png)

The highlighted text is only visible with jmi loaded. When I remove the mod the text is removed.

It also only appears when a waystone is nearby and the minimap is in the bottom right corner of the screen. I presume it is being drawn offscreen with the minimap in other locations. As you can see its size is affected by the the font scale for the minimap. It also seems to be slightly affected by the size of the minimap.

If possible, some way of removing (preferably) or moving this text would be appreciated.

**Comment by frank89722** [comment]
I'll look in to it tomorrow
But I guess this is a journeymap side issue

**Comment by mysticdrew** [comment]
Is this with 1.16.5? I found an issue related to text with 1.16.5 that will be resolved in beta 11

**Comment by Hjaldar** [comment]
Yes, sorry, it is with 1.16.5. I should have included all that info originally.

journeymap-1.16.5-5.8.0beta10.jar
jmi-1.16.5-0.6-34.jar

Issue discovered in modpack Enigmatica 6 version 0.5.24.

**Comment by mysticdrew** [comment]
> Yes, sorry, it is with 1.16.5. I should have included all that info originally.
> 
> journeymap-1.16.5-5.8.0beta10.jar jmi-1.16.5-0.6-34.jar
> 
> Issue discovered in modpack Enigmatica 6 version 0.5.24.
> 
> Many thanks to both of you

If you want to come into the Journeymap discord I can give you the current unrelease beta to see if it solves your issue.

**Comment by mysticdrew** [comment]
This is fixed in journeymap 5.8.0beta11 for 1.16.5-1.18.1

**Comment by Hjaldar** [comment]
Many thanks. Closing this is as resolved.

**Comment by sunnyrayyxo** [comment]
still broken

**Comment by mysticdrew** [comment]
> still broken

no, different issue I introduced. I know about it.

**Comment by frank89722** [comment]
Related to https://github.com/TeamJM/journeymap/issues/392 and https://github.com/TeamJM/journeymap/issues/390

For now, if you're using `journeymap-1.16.5-5.8.0beta12` and having waystone marker text got rendered on the strange position you can downgrade to 5.8.0beta11 for a temporary fix. Others have to wait for the next journeymap beta
