### ISSUE TITLE
[Request] FTB teams map

### ISSUE THREAD

**Issue by KMFrench1** [frank89722/JourneyMapIntegration#8]
Can you add integration with FTB teams, ftb chunks/teams adds a shared map that syncs the maps of everyone on a team. Ot would be great if that map could get merged the with Journey Map.  So I don't have to open a different map to see my team exploration progress.

**Comment by EnderMelody** [comment]
came here to ask about this as well, would be very nice to completely remove the need to use FTB Chunks as the main map.

**Comment by frank89722** [comment]
I believe this can only be done hackily since JM does all the mapping things on the client-side. That means this feature could easily break after JM update.

Anyways, I'll see what can I do when I have enough time to implement a new feature

**Comment by frank89722** [comment]
https://github.com/CivPlatform/map-sync 
I guess this is what you guys are looking for. I'll maybe integrate this mod instead of code everything myself since JMI is just a small client-side mod.
